### ISSUE TITLE
Since todays update cant connecto to Denon anymore

### ISSUE THREAD

**Issue by Levtos** [grzegorz914/homebridge-denon-tv#124]
Hello,

today i've updated your plugin, since them i can't control denon anymore. 
I got following message: 

[16.12.2021, 16:11:17] [DenonTv] Device: 192.168.178.31 Denon Main Zone, device info error: Error: timeout of 1000ms exceeded
[16.12.2021, 16:11:17] [DenonTv] Device: 192.168.178.31 Denon Main Zone, Disconnected.

I use your Plugin Version 3.13.16
Homebridge Version: 1.3.8
Node.js Version:  v16.13.1
Npm Version: v.8.3.0

**Comment by Innovary** [comment]
same problem here

**Comment by grzegorz914** [comment]
try restart your receiver

**Comment by Innovary** [comment]
> try restart your receiver

Thanks, works

**Comment by mogcraft** [comment]
Worked too. 

Just reseted my network connection from the denon. Since them it's works fine

**Comment by stephenjmcmahon** [comment]
@Innovary 
I used the power button to turn off/on the receiver - did you pull the plug or something? Same behavior on restart

@mogcraft 
I re-joined the WiFi connection but the issue persisted - did you do something else to 'reset' the network connection?

Apologies for commenting on closed thread...did what was recommended on here but still the issue is continuing - believe I'm missing something simple -_-

**Comment by grzegorz914** [comment]
@stephenjmcmahon 
What is your state right now?

Can you enable debug mode in the plugin config Advanced section and get the log?

**Comment by stephenjmcmahon** [comment]
@grzegorz914 

Prior to the below I enabled the logging from the Advanced Section, where is the output for this located? I'm using _Homebridge UI_ but can get it from the CLI if necessary

At this point, I've actually made it worse. I realized in a recent update it said to _"Note - after update to 3.15.0 need remove the accessory frome Home app and add it agai."_

So I (in the Home.app on iOS) _Long Pressed > Gear Cog >  Remove Accessory_ and restarted Homebridge but it did not re-appear in the Default Room. I tried removing the plugin and re-adding with the same accessory but I'm still not seeing it available at this time, triple checked that the IP was correct.

Again, I've made it worse, not sure what's up but this part isn't plug-in related -_- late here so will pick-up troubleshooting tomorrow.

**Comment by grzegorz914** [comment]
This accessory do not appear automatically in Home app, You need add it manually as in readme descriebed.

**Comment by lucasCFO** [comment]
Hi,

I have the same issue than @stephenjmcmahon ...
I can't add the accessory anymore whereas I'm doing it manually.

I've also tried the following without success:

- Install a previous version (v3.14.1) of the plug-in in homebridge UI
- Re-install the plug-in in homebridge UI
- Delete and add again the homebridge bridge inside the home app
- Create a child bridge in homebridge UI (dedicated to the plug-in)

But still, the denon accessory doesn't show up anymore... 😭

**Comment by grzegorz914** [comment]
Please all post the debug log direct after start homebridge.

**Comment by grzegorz914** [comment]
please also post  the config

**Comment by grzegorz914** [comment]
@lucasCFO 
your Denon is recognized and added to the bridge correct, You need add it to the Home app.
Open Home app press the + Add Accessory>>> More options, here should be displayed, if not clear homebridge cashe

````
[12/29/2021, 5:36:34 PM] [DenonTv] Device: 192.168.X.XXX Denon Main Zone, publishExternalAccessories.
[12/29/2021, 5:36:34 PM] Denon 3B33 is running on port XXXXX.
[12/29/2021, 5:36:34 PM] Please add [Denon 3B33] manually in Home app. Setup Code: XXX-XX-XXX
````

**Comment by lucasCFO** [comment]
Yeah I'm following the exact procedure:

<img width="754" alt="Capture d’écran 2021-12-29 à 18 59 34" src="https://user-images.githubusercontent.com/37216551/147690602-42074480-de08-4453-bcc9-0f51d361c3d3.png">
![IMG_7C2C2D159ADD-1](https://user-images.githubusercontent.com/37216551/147690646-b1401c74-f306-4afb-9be4-ad7c8dab07d7.jpeg)

But the accessory is not there...
I've checked all the rooms, even the default one...
Don't know what to do now...

**Comment by grzegorz914** [comment]
looks like Your accessory is already added, You need to remove or rest it first.

**Comment by grzegorz914** [comment]
try this #125

**Comment by lucasCFO** [comment]
Perfect it works again!
Thank you @grzegorz914 😉

**Comment by stephenjmcmahon** [comment]
@grzegorz914 I followed from thread #125 

First I **cat** the files listed in **/homebridge/persist** and found 2 pairs of Denon _(I did remove and re-install the plugin in hopes to resolve)_ so removed all 4 files _(4 because the matching AccessoryInfo & IdentifierCache)_

Restarted Homebridge and was greeted with the same error

```
[1/2/2022, 7:22:34 PM] [DenonTv] Device: 10.2.0.65 AVR-S750H Main Zone, device info error: Error: timeout of 2000ms exceeded
[1/2/2022, 7:22:34 PM] [DenonTv] Device: 10.2.0.65 AVR-S750H Main Zone, Disconnected.
```

From here, I went back to **/homebridge/persist** and removed all files as per your original recommendation on that thread but am still receiving the same error.

```
pi@pitester:~/docker/homebridge/persist $ sudo rm AccessoryInfo.*
pi@pitester:~/docker/homebridge/persist $ sudo rm IdentifierCache.*
pi@pitester:~/docker/homebridge/persist $ ls
pi@pitester:~/docker/homebridge/persist $
```

```
[1/2/2022, 7:22:44 PM] [DenonTv] Device: 10.2.0.65 AVR-S750H Main Zone, device info error: Error: timeout of 2000ms exceeded
[1/2/2022, 7:22:44 PM] [DenonTv] Device: 10.2.0.65 AVR-S750H Main Zone, Disconnected.
```

I've rebooted the entire RaspPi and still receiving the issue. IP of the Denon is the same _(10.2.0.65)_, Denon functioning fine otherwise.

I think we all agree it's not _actually_ a network issue, but for peace of mind the RaspPi can indeed ping the Denon.
```
pi@pitester:~ $ ping 10.2.0.65
PING 10.2.0.65 (10.2.0.65) 56(84) bytes of data.
64 bytes from 10.2.0.65: icmp_seq=1 ttl=63 time=1.70 ms
64 bytes from 10.2.0.65: icmp_seq=2 ttl=63 time=2.55 ms
64 bytes from 10.2.0.65: icmp_seq=3 ttl=63 time=8.05 ms
^C
--- 10.2.0.65 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 6ms
rtt min/avg/max/mdev = 1.704/4.101/8.051/2.814 ms
```


> So, all is OK here, the plugin is publish correct. You need go to /Homebridge/persist and /Homebridge/Accessories folder and remove manually old cashe.
^[From your comment in #125](https://github.com/grzegorz914/homebridge-denon-tv/issues/125#issuecomment-1002902880)

Do you need to have us additionally delete the file 'cachedAccessories' ?

```
pi@pitester:~/docker/homebridge/accessories $ ls
cachedAccessories  uiAccessoriesLayout.json
```

**Comment by grzegorz914** [comment]
@stephenjmcmahon your problem have nothing to do with #125 
First of all cykle Power in Your AVR. Next enable debug mode in plugin settings Advanced Section, restart HB and get the log.

**Comment by stephenjmcmahon** [comment]
@grzegorz914 it sure didn't lol - actually made it much worse for myself there for a minute going that route.

Debug mode is clutch though, thanks for including that. I did see that working but didn't end up needing it because.....I was able to get it back functional by _physically removing the power from the outlet_ and cycling it that way, prior I had just been using on/off (yes I know it hibernates...just thought that would be enough and didn't see anyone explicitly say to unplug it from outlet -_-)

_For future readers,_ after I deleted my entire cache from #125 the plugins would show normally in Homebridge but show as non-connectable in Home.app. I was able to resolve this by removing the Homebridge _bridge_ itself from Home.app entirely so that it removed all accessories then re-adding the bridge, as soon as that re-paired everything showed back up.
